[package]
name = "abc125_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
proconio = "0.4.5"
my-segtree = { path = "../my-segtree" }
